### ISSUE TITLE
filtering the result needed 

### ISSUE THREAD

**Issue by ghassanmas** [FACK1/Beauty#53]
https://github.com/FACK1/Beauty/blob/9b9fd916ac116cd49da420cdd949c2ef3d92101f/src/search.js#L4-L9

I don't think Line 4, Line 5 and 7 are needed, since you haven't changed anything regarding the object key value

**Comment by RazanTayyem** [comment]
:+1: 
Done

**Comment by ghassanmas** [comment]
Good job, next time the reference in the commit please :pray:
